name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shards: [1, 2, 3]
        browser: [chromium, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browser
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Install Allure
        run: npm i -g allure-commandline

      - name: Run tests
        run: |
          npx playwright test \
            --shard=${{ matrix.shards }}/3 \
            --project=${{ matrix.browser }} \
            --reporter=list,allure-playwright

      - name: Generate Allure report
        if: always()
        run: |
          allure generate allure-results -o allure-report/${{ matrix.browser }}-${{ matrix.shards }} --clean

      - name: Store report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 14

      - name: Store traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: traces-${{ matrix.browser }}-${{ matrix.shards }}
          path: test-results
          retention-days: 7

  publish-report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report